name: Test

on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx yarn
      - run: npx yarn run build
      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          working-directory: "."
          test-command: "npx jest"
